FROM node:20-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy lock file
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY .npmrc ./

# Copy project files
COPY package.json ./
COPY lib ./lib
COPY artifacts/api-server ./artifacts/api-server
COPY tsconfig.json tsconfig.base.json ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Build API
RUN pnpm --filter @workspace/api-server run build

EXPOSE 3000

# Run API server
CMD ["pnpm", "--filter", "@workspace/api-server", "start"]
